name: CustomMessages
description: Plugin that allows you to change advancement and death messages
main: me.anxietie.customMsgs.Main
version: 1.1
api-version: 1.18
author: Anxietie
website: "https://github.com/Anxietie/Custom-Messages.git"

commands:
   custommessage:
      description: Main command for Custom Messages
      aliases: [cmsg, cmsgs, cmessage]
permissions:
   cmsg.*:
      description: Gives all permissions for Custom Messages
      children:
         cmsg.reload: true
         cmsg.set: true
         cmsg.get: true
   cmsg.set:
      description: Gives permission to set values in the config
      default: false
   cmsg.get:
      description: Gives permission to view a value at a path in the config
      default: false
   cmsg.reload:
      description: Gives permission to reload the config.yml file
      default: false